//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_SOP.QueryService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QueryService.QueryServiceSoap")]
    public interface QueryServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryItemNoByWo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryItemNoByWo(string woNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryItemNoByWo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryItemNoByWoAsync(string woNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryItemNoBySn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryItemNoBySn(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryItemNoBySn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryItemNoBySnAsync(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryBarcodeStation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable QueryBarcodeStation(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryBarcodeStation", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> QueryBarcodeStationAsync(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryKeyPartsBySn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryKeyPartsBySn(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryKeyPartsBySn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> QueryKeyPartsBySnAsync(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryRepair_InfoBySn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryRepair_InfoBySn(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryRepair_InfoBySn", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> QueryRepair_InfoBySnAsync(string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryWO_Info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryWO_Info(string sWoNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryWO_Info", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> QueryWO_InfoAsync(string sWoNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryServiceSoapChannel : E_SOP.QueryService.QueryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceSoapClient : System.ServiceModel.ClientBase<E_SOP.QueryService.QueryServiceSoap>, E_SOP.QueryService.QueryServiceSoap {
        
        public QueryServiceSoapClient() {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string QueryItemNoByWo(string woNo) {
            return base.Channel.QueryItemNoByWo(woNo);
        }
        
        public System.Threading.Tasks.Task<string> QueryItemNoByWoAsync(string woNo) {
            return base.Channel.QueryItemNoByWoAsync(woNo);
        }
        
        public string QueryItemNoBySn(string serialNo) {
            return base.Channel.QueryItemNoBySn(serialNo);
        }
        
        public System.Threading.Tasks.Task<string> QueryItemNoBySnAsync(string serialNo) {
            return base.Channel.QueryItemNoBySnAsync(serialNo);
        }
        
        public System.Data.DataTable QueryBarcodeStation(string serialNo) {
            return base.Channel.QueryBarcodeStation(serialNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> QueryBarcodeStationAsync(string serialNo) {
            return base.Channel.QueryBarcodeStationAsync(serialNo);
        }
        
        public System.Data.DataSet QueryKeyPartsBySn(string serialNo) {
            return base.Channel.QueryKeyPartsBySn(serialNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> QueryKeyPartsBySnAsync(string serialNo) {
            return base.Channel.QueryKeyPartsBySnAsync(serialNo);
        }
        
        public System.Data.DataSet QueryRepair_InfoBySn(string serialNo) {
            return base.Channel.QueryRepair_InfoBySn(serialNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> QueryRepair_InfoBySnAsync(string serialNo) {
            return base.Channel.QueryRepair_InfoBySnAsync(serialNo);
        }
        
        public System.Data.DataSet QueryWO_Info(string sWoNo) {
            return base.Channel.QueryWO_Info(sWoNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> QueryWO_InfoAsync(string sWoNo) {
            return base.Channel.QueryWO_InfoAsync(sWoNo);
        }
    }
}
